### PR TITLE
Fix bug: all connections are not reuse

### PR DESCRIPTION
**Pull request by davidwudv**
To ensure http.Client connection reuse, must do two things:
1.Read until Response is complete.
2.Call Body.Close().

you can test it

### CODE REVIEW

**Comment by missedone** [comment]
this is duplicate with PR #70

**Comment by davidwudv** [comment]
@missedone sorry, I didn't notice that before

**Comment by rakyll** [comment]
See my comment on https://github.com/rakyll/boom/issues/60#issuecomment-153485429. If socket is not being reused after closing a response body, it is a net/http bug.

**Comment by davidwudv** [comment]
@rakyll My go version is 1.5.1, I test your code and watch netstat. The socket is not being reused, and i  saw a lot of time_wait status connections.

**Comment by yuankui** [comment]
```
// Body represents the response body.
	//
	// The http Client and Transport guarantee that Body is always
	// non-nil, even on responses without a body or responses with
	// a zero-length body. It is the caller's responsibility to
	// close Body. The default HTTP client's Transport does not
	// attempt to reuse HTTP/1.0 or HTTP/1.1 TCP connections
	// ("keep-alive") unless the Body is read to completion and is
	// closed.
	//
	// The Body is automatically dechunked if the server replied
	// with a "chunked" Transfer-Encoding.
	Body io.ReadCloser
```

But reading the content of body is really costing time

**Pull request closed without merging**
