### PR TITLE
add option to specify filename

### PR DESCRIPTION
**Pull request by tquach**
Fixes #53

Uses `curl` style argument parsing:

```
Options:
...
  -d  HTTP request body. If you start the data with the letter @, the rest should 
      be a file name to read the data from.
```

### CODE REVIEW

**Comment by tquach** [comment]
bump

**Comment by missedone** [comment]
+1
this looks quite and quite convenient for use

**Comment by michelesr** [comment]
Very useful. I rebased upstream with your commit in f04b4bc6b4f4f68c53be953bd2cbeee1005cb460

**Comment by tquach** [comment]
@missedone @rakyll Pull request has been re-based. Would you prefer to use `-f` as the flag instead of `-d`?

**Comment by rakyll** [comment]
"@/Users/jbd/whatever" is a perfectly valid request body.

I'd prefer it to have its own flag.

**Comment by tquach** [comment]
Sure can do. What takes precedence, `-d` or `-f`?

**Comment by rakyll** [comment]
The project has moved to https://github.com/rakyll/hey. Closing the PRs on this legacy repo.

**Pull request closed without merging**
