### PR TITLE
Allow overriding the HTTP Host header

### PR DESCRIPTION
**Pull request by rafael84**

### CODE REVIEW

**Comment by rafael84** [comment]
Any feedback?

**Comment by rakyll** [comment]
This is already achievable with the -H flag.

We only have a helper -A flag for the Accept flag because it is commonly required.

**Comment by rakyll** [comment]
According to https://github.com/rakyll/boom/issues/76, -H cannot be used to set the host. Is it still true?

**Comment by rafael84** [comment]
Yes, it is. 

I forgot to mention #76 earlier, sorry.

**Comment by hodgesds** [comment]
Still noticing this, any chance of this getting merged?

**Comment by rakyll** [comment]
@rafael84, did you sign a Google CLA before? If not, could you please sign https://cla.developers.google.com/about/google-individual? I can't merge PRs without the agreement since the project is copyrighted to Google.

**Comment by rafael84** [comment]
Done.

Em 26/07/2016 21:10, "Jaana Burcu Dogan" <notifications@github.com>
escreveu:

**Comment by rakyll** [comment]
Thanks!

**Pull request merged**
